--APLICAÇÃO 1 SCHEMA(APPCRUD) SENHA(ORACLE11G)
CREATE USER APPCRUD IDENTIFIED BY ORACLE1G 
--DEFAULT TABLESPACE TBS_APPCRUD_DATA; 
DEFAULT TABLESPACE USERS; 
GRANT CREATE SESSION, 
ALTER SESSION, CREATE DATABASE LINK,
CREATE MATERIALIZED VIEW, CREATE PROCEDURE, CREATE PUBLIC SYNONYM,
CREATE ROLE, CREATE SEQUENCE, CREATE SYNONYM, CREATE TABLE, 
CREATE TRIGGER, CREATE TYPE, CREATE VIEW, UNLIMITED TABLESPACE, 
CONNECT, RESOURCE TO APPCRUD; 
 --Desbloqueando um usuário
ALTER USER APPCRUD identified by ORACLE11G account unlock;
