DECLARE
    CURSOR CURSOR_PF(NM_PF_P VARCHAR2) IS
        SELECT CD_PESSOA_FISICA, NM_PESSOA_FISICA FROM PESSOA_FISICA 
            WHERE NM_PESSOA_FISICA LIKE :NM_PF_P;
BEGIN
    FOR C1 IN CURSOR_PF(NM_PF_P => 'CAMILA VILEIRA') LOOP
        DBMS_OUTPUT.PUT_LINE('CÓDIGO: ' || C1.CD_PESSOA_FISICA ||
            ' NOME: ' || C1.NM_PESSOA_FISICA);
        --EXIT WHEN (é opcional)
        --EXIT WHEN C1.CD_PESSOA_FISICA = 1131;
    END LOOP;        
END;
    