--CURSOR
DECLARE
    CURSOR CURSOR_PF IS
        SELECT CD_PESSOA_FISICA, NM_PESSOA_FISICA
        FROM PESSOA_FISICA ORDER BY 2;
    
    CD_PESSOA_FISICA_W NUMBER;
    NM_PESSOA_FISICA_W VARCHAR2(100);
        
BEGIN
    OPEN CURSOR_PF;
    LOOP
    FETCH CURSOR_PF INTO  CD_PESSOA_FISICA_W, NM_PESSOA_FISICA_W;
    EXIT WHEN CURSOR_PF%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('CÓDIGO : ' || CD_PESSOA_FISICA_W ||
                ' NOME : ' || NM_PESSOA_FISICA_W);
    END LOOP;
END;