--CURSOR COM PARÂMETROS
DECLARE
    --definir qtos parâmetros terá o cursor
    CURSOR CURSOR_PF(CD_PESSOA_P NUMBER)IS
        SELECT CD_PESSOA_FISICA, NM_PESSOA_FISICA
            FROM PESSOA_FISICA WHERE CD_PESSOA_FISICA = CD_PESSOA_P;
    
    V_PF CURSOR_PF%ROWTYPE;
        
BEGIN
    --OPEN CURSOR_PF(CD_PESSOA_P => 1129);
    --OU 
    OPEN CURSOR_PF(CD_PESSOA_P => :pCDPF);
    LOOP
    FETCH CURSOR_PF INTO  V_PF;
    EXIT WHEN CURSOR_PF%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('CÓDIGO : ' || V_PF.CD_PESSOA_FISICA ||
                ' NOME : ' || V_PF.NM_PESSOA_FISICA);
    END LOOP;
END;