--VALORES NULOS
SELECT
    first_name,
    last_name,
    salary,
    commission_pct, 
    commission_pct * SALARY AS VAL_COMM   
FROM
    employees
WHERE 
    commission_pct IS NULL;

--USANDO O NVL PARA SOMAR ONDE UM VALOR É NULO
SELECT
    first_name,
    last_name,
    salary,
    NVL(commission_pct, 0) + 10,
    commission_pct * SALARY AS VAL_COMM   
FROM
    employees
WHERE 
    commission_pct IS NULL;
    
--RETORNANDO SOMENTE EMPREGADOS QUE PPOSSUEM COMISSÃO
SELECT
    first_name,
    last_name,
    salary,
    commission_pct, 
    commission_pct * SALARY AS VAL_COMM   
FROM
    employees
WHERE 
    commission_pct IS NOT NULL;


SELECT
    first_name ||' '||  last_name AS NAME,    
    SALARY, 
    SALARY + (SALARY/100 * 10) AS "SAL_AUMENTADO_10%"
FROM 
    EMPLOYEES
WHERE 
    DEPARTMENT_ID = 20;
    
--VERIFICAR QUANTAS LINHAS TEM NA TABELA COUNT(1) OU COUNT(2) ... OU COUNT(*)
SELECT COUNT(*)
FROM EMPLOYEES;
--VERIFICAR QUANTOS NOMES ÚNICOS TEM NA TABELA
SELECT COUNT(DISTINCT first_name)
    FROM EMPLOYEES;
    
--DISTINCT FIRST_NAME REPETIDOS
SELECT DISTINCT FIRST_NAME
FROM EMPLOYEES;

--QUEM SÃO ESSES NOMES?
SELECT  FIRST_NAME
FROM EMPLOYEES
GROUP BY FIRST_NAME
HAVING COUNT(FIRST_NAME) = 2;

--DESCREVE A TABELA
DESC EMPLOYEES;

--CUIDADO NESSE TIPO DE CONSULTA
--PRECEDÊNCIA NO SELECT

SELECT
    EMPLOYEE_ID, JOB_ID, DEPARTMENT_ID    
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 60
AND JOB_ID = 'IT_PROG'
OR JOB_ID = 'AD_VP';

SELECT
    EMPLOYEE_ID, JOB_ID, DEPARTMENT_ID    
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 60
AND (JOB_ID = 'IT_PROG'
OR JOB_ID = 'AD_VP');

SELECT
    FIRST_NAME, LAST_NAME, 
    JOB_ID, SALARY, HIRE_DATE
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 30
ORDER BY HIRE_DATE DESC;