SELECT * FROM PESSOA_JURIDICA_CURSO;
SELECT * FROM PEDIDOS_CURSO;

--INNER JOIN
SELECT PJ.CD_CNPJ, PJ.DS_RAZAO_SOCIAL, PED.NR_PEDIDO, PED.DT_ORDEM_COMPRA FROM PESSOA_JURIDICA_CURSO PJ
INNER JOIN PEDIDOS_CURSO PED ON PJ.CD_CNPJ = PED.CD_CNPJ;

SELECT PJ.CD_CNPJ, PJ.DS_RAZAO_SOCIAL, PED.NR_PEDIDO, PED.DT_ORDEM_COMPRA FROM PESSOA_JURIDICA_CURSO PJ
JOIN PEDIDOS_CURSO PED ON PJ.CD_CNPJ = PED.CD_CNPJ;

--WHERE

SELECT PJ.CD_CNPJ, PJ.DS_RAZAO_SOCIAL, PED.NR_PEDIDO, PED.DT_ORDEM_COMPRA FROM PESSOA_JURIDICA_CURSO PJ, PEDIDOS_CURSO PED
WHERE PJ.CD_CNPJ = PED.CD_CNPJ;

--LEFT OUTER JOIN
SELECT PJ.CD_CNPJ, PJ.DS_RAZAO_SOCIAL, PED.NR_PEDIDO, PED.DT_ORDEM_COMPRA FROM PESSOA_JURIDICA_CURSO PJ
LEFT OUTER JOIN PEDIDOS_CURSO PED ON PJ.CD_CNPJ = PED.CD_CNPJ;

--QUANDO USAR? EX: QUEM É O CLIENTE QUE NUNCA FEZ COMPRA
SELECT PJ.CD_CNPJ, PJ.DS_RAZAO_SOCIAL, PED.NR_PEDIDO, PED.DT_ORDEM_COMPRA FROM PESSOA_JURIDICA_CURSO PJ
LEFT OUTER JOIN PEDIDOS_CURSO PED ON PJ.CD_CNPJ = PED.CD_CNPJ
WHERE PED.NR_PEDIDO IS NULL;

--COMO SERIA SE FOSSE ANTIGAMENTE COM O WHERE 
SELECT PJ.CD_CNPJ, PJ.DS_RAZAO_SOCIAL, PED.NR_PEDIDO, PED.DT_ORDEM_COMPRA FROM PESSOA_JURIDICA_CURSO PJ, PEDIDOS_CURSO PED 
WHERE PJ.CD_CNPJ = PED.CD_CNPJ(+);

--RIGHT OUTER JOIN
SELECT PJ.CD_CNPJ, PJ.DS_RAZAO_SOCIAL, PED.NR_PEDIDO, PED.DT_ORDEM_COMPRA FROM PESSOA_JURIDICA_CURSO PJ
RIGHT OUTER JOIN PEDIDOS_CURSO PED ON PJ.CD_CNPJ = PED.CD_CNPJ;

--COMO SERIA SE FOSSE ANTIGAMENTE COM O WHERE 
SELECT PJ.CD_CNPJ, PJ.DS_RAZAO_SOCIAL, PED.NR_PEDIDO, PED.DT_ORDEM_COMPRA FROM PESSOA_JURIDICA_CURSO PJ, PEDIDOS_CURSO PED 
WHERE PJ.CD_CNPJ(+) = PED.CD_CNPJ;

--FULL OUTER JOIN
SELECT PJ.CD_CNPJ, PJ.DS_RAZAO_SOCIAL, PED.NR_PEDIDO, PED.DT_ORDEM_COMPRA FROM PESSOA_JURIDICA_CURSO PJ
FULL OUTER JOIN PEDIDOS_CURSO PED ON PJ.CD_CNPJ = PED.CD_CNPJ;

--FULL OUTER JOIN NÃO TEM A SINTAXE REPRESENTATIVA COM WHERE



