--MANIPULAR DADOS COM CURSORES

--O CURSOR VAI REALIZAR ATUALIZAÇÃO DOS REGISTROS  
SELECT NM_USUARIO_NREC FROM PESSOA_FISICA;
BEGIN
    FOR  CURSOR_USER IN (SELECT 'LEANDRO' NM_USUARIO_NREC FROM PESSOA_FISICA) 
    
    LOOP
        UPDATE PESSOA_FISICA SET NM_USUARIO_NREC = CURSOR_USER.NM_USUARIO_NREC;
    END LOOP;
    
    COMMIT;

END;