--UNION
SELECT CD_PESSOA_FISICA, NM_PESSOA_FISICA FROM PESSOA_FISICA
UNION
SELECT CD_PESSOA_FISICA, '' NM_PESSOA_FISICA  FROM TITULO_RECEBER;

SELECT CD_PESSOA_FISICA FROM PESSOA_FISICA
UNION
SELECT CD_PESSOA_FISICA FROM TITULO_RECEBER;
--COMO 1125 TEM DT_NASCIMENTO = DT_VENCIMENTO O UNION FAZ UM DISTINCT
SELECT CD_PESSOA_FISICA, DT_NASCIMENTO FROM PESSOA_FISICA
UNION
SELECT CD_PESSOA_FISICA, DT_VENCIMENTO FROM TITULO_RECEBER;

--UNION ALL
SELECT CD_PESSOA_FISICA FROM PESSOA_FISICA
UNION ALL
SELECT CD_PESSOA_FISICA FROM TITULO_RECEBER;

SELECT CD_PESSOA_FISICA, DT_NASCIMENTO FROM PESSOA_FISICA
UNION ALL
SELECT CD_PESSOA_FISICA, DT_VENCIMENTO FROM TITULO_RECEBER;