SELECT * FROM FUNCIONARIO;

DECLARE
    W_VL_SALARIO        NUMBER(10,2);
    W_NR_SEQ_FUNC       NUMBER := 1;
BEGIN
    SELECT VL_SALARIO
        INTO W_VL_SALARIO
    FROM FUNCIONARIO
    WHERE NR_SEQ_FUNC = W_NR_SEQ_FUNC;
    
    DBMS_OUTPUT.put_line(W_VL_SALARIO);
END;

    SELECT VL_SALARIO
  --      INTO W_VL_SALARIO
    FROM FUNCIONARIO
    WHERE NR_SEQ_FUNC = 1;